### ISSUE TITLE
Load asset with the name by the selected one and not by default

### ISSUE THREAD

**Issue by trynx** [PhaserEditor2D/PhaserEditor2D-v3#106]
When selecting an asset to show on an object at the canvas, if selecting an asset with the same name, the object will still show the same asset, which is the first one depend on the package name. 

e.g. Have asset by the name `background`, and I have the same key name 'background' but in 2 different packages named, packageA and packageB, it will always use packageA asset, even when trying to use asset from packageB.

[Pay user]

**Comment by PhaserEditor2D** [comment]
We did it this way in v1 of the editor and it created certain troubles. The problem is that renaming or moving the pack file will break the scenes. So it will require to do a lot of refactoring work, that is what we did in v1.

For now, in v3, we don't have refactoring tools, so you have to update all the scene files manually.

**Comment by PhaserEditor2D** [comment]
Also, in Phaser is works the same, a texture is identified by a name, so I would like to follow the same logic in the editor.

In the end, using the same name for different assets is not a good idea :(
