### ISSUE TITLE
Prefabs have everything locked by default

### ISSUE THREAD

**Issue by ItsGravix** [PhaserEditor2D/PhaserEditor2D-v3#108]
Was it on purpose for prefabs to have their properties locked by default? I usually scale my container prefabs and it gets annoying to unlock the transform/instance properties every time.
![image](https://user-images.githubusercontent.com/9307505/106829355-fbf21180-6659-11eb-859d-0acf82e639bc.png)

**Comment by PhaserEditor2D** [comment]
Yes, that's the goal of prefabs, allow you to change the prefab and propagate that change in all the instances.
It's true the transformation is something you would like to change very often. Maybe a general solution is allowing you to set "default unlocked properties" in the prefab scene. This means, if in the prefab you mark a property as unlocked by default, it will be unlocked in all the instances.

**Comment by ItsGravix** [comment]
@PhaserEditor2D Yes, a way to set defaults would be a great option.

**Comment by PhaserEditor2D** [comment]
Hi, I was working on this but.. I think it is complicating everything.

What do you think if we do something different? Instead of label the unlcoked-by-default properties, it can provide a shortcut to unlock a property.

For example, when you enable the scale tool (`S`) but the scale property is locked, it can show a message like "the scale property is locked, do you want to unlock it?". If you answer Yes, then the property is unlocked.

**Comment by ItsGravix** [comment]
@PhaserEditor2D That would be fine.

**Comment by PhaserEditor2D** [comment]
That was fast :)

**Comment by PhaserEditor2D** [comment]
Done. It now shows a message asking for unlock the affected properties.

![image](https://user-images.githubusercontent.com/12187299/116436830-c99c1e80-a81a-11eb-83d1-7c07e3d34180.png)

It works with the scale tool, rotate tool, origin tool ,and size tool.
