### ISSUE TITLE
Change the tint of the Image to BitmapText in one field

### ISSUE THREAD

**Issue by BenoitFreslon** [PhaserEditor2D/PhaserEditor2D-v3#201]
I will be cool if we can change the full color of a text and an image instead to change the 4 tints each time.
![image](https://user-images.githubusercontent.com/758680/159924949-aba0c6ae-3ef0-4de8-82ab-7dc19483043a.png)

**Comment by PhaserEditor2D** [comment]
A single tint value complicates the whole thing. Look in the Phaser, the [tint](https://github.com/photonstorm/phaser/blob/d67c93646cbfe8ba5997954f8af29a8f3f9e8e91/src/gameobjects/components/Tint.js#L183) property is write-only, it is just a helper property for setting the same value to all `tint*` properties.

Simulating a write-only property in Phaser Editor is complex because the way it serialize and code-generate the properties of prefab instances. I did try it, but it is not clean and breaks the general rules.

Maybe, I can add an option in the section's three-dots menu for setting the same value to all the tint properties taking as reference the Tint Top Left property's value. If it is the case of a prefab instance and there are locked tint properties, then it will ask for unlocking them or abort the operation.

What do you think?
