### ISSUE TITLE
Add Phaser.Physics.Arcade.Sprite game object type to editor

### ISSUE THREAD

**Issue by CodestarGames** [PhaserEditor2D/PhaserEditor2D-v3#211]
I'm working on a couple of games that use arcade physics sprites and it would be nice to be able to use them directly in the editor and be able to adjust their physics bounding boxes. Right now I'm using a physicsBounds component where I have to set the x, y, width, and height manually with no visual indicator, which is kind of a pain. It would be great if these could behave similar to how the tilesprite gameobject does in the editor.

**Comment by DriesVG-ui** [comment]
Indeed. It needs a simpeler method for this...

**Comment by PhaserEditor2D** [comment]
Hi @DriesVG-ui! What do you mean with a simpler method?

**Comment by DriesVG-ui** [comment]
Well. I use phaser 3 and i just type for example: this player= this.physics.add. Sprite(...) And it's solved...

Not in the editor it seems. When i adapt the code it works at the beginning. But from the moment i drag that image on the scene editor it changes the whole thing back into const player= this.add.sprite(...)....it removes everything you wrote which is very frustrating and forces you to find a more complex way to add physics...

**Comment by PhaserEditor2D** [comment]
Oh yes, you cannot modify the code generated by the compiler. You should write only in the "protected sections" of the code.

You are right that the editor should provide a straightforward method for adding a physics sprite. In the meantime, probably the most simple thing is to create a user component for this. Let's say, a AddBody component that will add the object to the physics.

So:

1- You add the image to the scene
2- You add the AddBody component to the image.

Sure, you will need to set the body size, velocity, etc... by hand, unless you create user properties for this.

But yes, the issue is here because we need to simplify the whole thing, including visual manipulators like it is available in v1 of the editor.

**Comment by DriesVG-ui** [comment]
Thanks.

Oh I found another way too to add physics to my objects. You have to change your scope from "method" to "class" or "public" for your item. 

That way the editor creates automaticly your object like **this.dino=dino**.

Sooo....in that case you can easly use "this.dino" outside the editorCreate() section (cause it's not const anymore...) and in your create() section you just add "this.physics.world.enable(this.dino)" and you are off to go. Even if I drag the dino item on the scene editor it still contains its physics...so that's also a good to do it for now.

Thanks for the quick replies. Sorry I seem to rush through it...it seems interesting but there is just a lot to learn for me...

Greetings

**Comment by PhaserEditor2D** [comment]
Yes! Nice. The editor provides some tools that may help you on adding behaviors not supported by default. As I mentioned to you, try making a user component for physics:

https://help.phasereditor2d.com/v3/scene-editor/prefab-user-properties-create.html

Or you can create a PhysicsSprite as a prefab black box: 

https://help.phasereditor2d.com/v3/scene-editor/prefab-black-box.html

Or just encapsulate all your physics objects as prefabs: Player prefab, Pickable prefab, Enemy prefab, etc... And set the physics there, in the prefab constructor.

**Comment by PhaserEditor2D** [comment]
Hi @CodestarGames @DriesVG-ui @michaelgundlach I'm working on this!

Would you like to try a beta release?

Sure, it will have a visual tool for changing the body size.

<img width="308" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/12187299/192008928-ec0dd82b-e3cd-46a4-8534-ad3fd06aa464.png">
<img width="307" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/12187299/192009006-d3a10e61-ff5f-4b22-840f-8b32e89f56d2.png">
<img width="308" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/12187299/192009031-ee1ae6d9-0cc3-4aa2-a9c4-cc21c71b4088.png">

**Comment by DriesVG-ui** [comment]
Ok nice...yes i am interested.

**Comment by PhaserEditor2D** [comment]
Done. Please, take the binaries from the beta release:

https://github.com/PhaserEditor2D/PhaserEditor2D-v3/releases/tag/v3.35.0-beta.0

**Comment by DriesVG-ui** [comment]
Ok I have tested it. Looks good! Thanks for making phaser editor better and better...

**Comment by PhaserEditor2D** [comment]
Great! Thanks!
