### ISSUE TITLE
If a tilemap layer is placed inside a container it will fail to load because the tilemapId is undefined

### ISSUE THREAD

**Issue by jrabek** [PhaserEditor2D/PhaserEditor2D-v3#229]
* Phaser Editor 2D Version: Version 3.33.2 (3.33.2)
* Operating System: Mac
* Web Browser and version: N/A

## Description
If a tilemap layer is placed inside a container it will fail to load because the tilemapId is undefined.  Guessing because it is searching only inside the container for the tileset?  The only way to fix it is to manually edit the scene file and remove the tilemap layers from the container.

**Comment by PhaserEditor2D** [comment]
Yes, it happens because the container is making the children using first the default data, but a tilemap layer requires the tilemap to be created. It is not like the other game objects, which don't require any other object in the scene. It means, you cannot create an empty tilemaplayer and later link it to a tilemap.

I will work on this.

**Comment by PhaserEditor2D** [comment]
Done.

**Comment by jrabek** [comment]
Basically treating all the tilemap layers as a single object.
