### ISSUE TITLE
Add Support for Safari 

### ISSUE THREAD

**Issue by NickChowHK** [PhaserEditor2D/PhaserEditor2D-v3#24]
![image](https://user-images.githubusercontent.com/10241183/82624826-23ad6080-9c16-11ea-9f11-98a506f30e6d.png)

I tried to open the editor via Safari but got Unhandled Promise Rejection Error like the above image. Safari finally only shows a blank page.

**Comment by PhaserEditor2D** [comment]
Hi,

What version of Safari?

**Comment by NickChowHK** [comment]
> Hi,
> 
> What version of Safari?

Version 13.1 (15609.1.20.111.8)

**Comment by PhaserEditor2D** [comment]
Hi @NickChowHK 

The problem is that Safari does not support the EventTarget constructor: 

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget

I do extensive use of it. I created a branch to migrate it to other event framework but it creates a bit of mess in the code. There are polyfill options and maybe it will be the final solution. In the meantime, please, test this build I did for you and tell me if it works now. I have an old mac-mini with an old macOS (El Capitan), and I cannot test the editor in the latest Safari. In the Safari I have (v11) it runs well until it finds the `flatMap` function that is not supported, but it should run in your Safari version.

[PhaserEditor2D-3.1.0-macos.zip](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/4671163/PhaserEditor2D-3.1.0-macos.zip)

**Comment by NickChowHK** [comment]
> Hi @NickChowHK
> 
> The problem is that Safari does not support the EventTarget constructor:
> 
> https://developer.mozilla.org/en-US/docs/Web/API/EventTarget
> 
> I do extensive use of it. I created a branch to migrate it to other event framework but it creates a bit of mess in the code. There are polyfill options and maybe it will be the final solution. In the meantime, please, test this build I did for you and tell me if it works now. I have an old mac-mini with an old macOS (El Capitan), and I cannot test the editor in the latest Safari. In the Safari I have (v11) it runs well until it finds the `flatMap` function that is not supported, but it should run in your Safari version.
> 
> [PhaserEditor2D-3.1.0-macos.zip](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/4671163/PhaserEditor2D-3.1.0-macos.zip)

Yeah, it is solved by this version.

**Comment by PhaserEditor2D** [comment]
Hi @NickChowHK 

Thanks for testing.

I found another issue with Safari, the drag image is not shown. But the solution is not going to be part of this release.

https://github.com/PhaserEditor2D/PhaserEditor2D-v3/issues/29
