### ISSUE TITLE
Adding a Audio Game object Block for Phaser Editor

### ISSUE THREAD

**Issue by gregwoodsfrontier** [PhaserEditor2D/PhaserEditor2D-v3#276]
As title, adding a Audio game object block will benefit us game devs. We can just add in the audio key in the editor and attach more script nodes on controlling the SFX / background music etc.

**Comment by PhaserEditor2D** [comment]
Do you mean, you would like the editor to generate something like this:

```
const music = this.sound.add("background-music");
```

And then control by adding script nodes to the `music` object?

What's the difference with creating an `AudioScriptNode`?

Maybe what we should do is, instead of creating a new type of object, is creating a small framework of script nodes for managing and playing audio. What do you think?

**Comment by gregwoodsfrontier** [comment]
A small framework also helps as well. I think it might be more suitable for
audio controls.

**Comment by PhaserEditor2D** [comment]
I agree.

Any idea about the kind of nodes we should create is very welcome.

**Comment by PhaserEditor2D** [comment]
Recently I find the events system in Phaser very handy for decoupling the different parts of a game. It may apply to audio management.

For example, let's say I want to play a sound when the player jumps. Instead of playing the audio by calling any of the Phaser API, it can emit a `"play-audio-fx"` event, in the context of the whole game. Then, a sound manager can listen to that event and play the corresponding audio file. If the audio fx is muted, then it will ignore it, etc... For example, it can handle the audio fx volume settings.

I mean, the gameplay implementation doesn't have to deal with the audio implementation, else it will fire an event, that is handled by an audio service.

**Comment by PhaserEditor2D** [comment]
But ok, it may be good for a long game, but for a demo or prototype, we should provide a straight method for playing audios.

**Comment by gregwoodsfrontier** [comment]
I think that script nodes are mostly for code organisation. If I want to
play, it would just add the audio and then play it.

But I think a AudioManager node would be very useful.

**Comment by PhaserEditor2D** [comment]
Hi. Now we have the scripts-audio library. Take a look: https://github.com/PhaserEditor2D/phasereditor2d-scripts-audio

If there is any feature you would like to have there, please, let me know.
